version: "3.3"
services:
#  application:
#    build: ./application/
#    ports:
#      - "8080:8080"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind 
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
  victoriametrics:
    image: victoriametrics/victoria-metrics
    ports:
      - 8428:8428
      - 4242:4242
    command:
      - "--storageDataPath=/storage"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
volumes:
  grafanadata: